name: build

on: 
  push:
    branches: [ main ]
    paths: [ '**.java', '.github/workflows/jacoco.yml', 'pom.xml' ]
  pull_request:
    branches: [ main ] 
  
jobs:
  jacoco-java-maven: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: build with Maven
        run: mvn -B package -Pcoverage

      - name: log coverage percentages to workflow output
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

      - name: get coverage info
        run: |
          echo "Total coverage  ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Chenged files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
        
